name: Code Review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "*"
      - "!infra/*"
      - "!.github/*"

env:
  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

jobs:
  code_review:
    runs-on: ubuntu-22.04

    steps:
      - name: Check-out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      # Check where find DANGER_GITHUB_API_TOKEN secret
      - name: Danger CI
        if: ${{ env.DANGER_GITHUB_API_TOKEN != '' }}
        run: yarn danger ci
        shell: bash
        env:
          DANGER_GITHUB_API_TOKEN: ${{ env.DANGER_GITHUB_API_TOKEN }}
          
      - name: Unit tests exec
        run: yarn test:coverage --watchAll=false