name: Deploy CDN PNPG

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "!.github/**"
      - "!.devops/**"
      - "!infra/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-version"
      - "!CODEOWNERS"
  
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:
  release_and_deploy:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_cdn_vite_cdn.yml@main
    name: "Release [${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}]"
    secrets: inherit
    with:
      environment: ${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}
      file_environment: ${{ format('fe_{0}_pnpg.env', (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev') }}
      storage_account_name: weupnpgcheckoutst01
      profile_name: weu-pnpg-checkout-afd-01
      endpoint_name: weu-pnpg-checkout-fde-01
      resource_group_name: weu-pnpg-checkout-fe-rg
      blob_container_name: $web
      base_path: token-exchange
